# Generated by Django 5.2.14 on 2026-06-02 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
    ]
